Repository theforeman/smart-proxy, pull requests merged in 2018-04, with the labels that each got.

#571 Fixes #23031 - parse server duid's with nested double quotes
  modules/dhcp_common/isc/configuration_parser.rb
  test/dhcp/conf_parser_test.rb
Labels: Needs testing

#573 Fixes #2677 - Removed sinatra workaround for "accept" headers
  lib/sinatra-patch.rb
  lib/smart_proxy_main.rb
Labels: Needs testing

#574 Update the README
  README.md
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#575 Fixes #23166 - MAC DHCP CRUD not case sensitive
  modules/dhcp/dhcp_api.rb
  test/dhcp/dhcp_api_test.rb
Labels: Needs testing, Not yet reviewed

#572 Fixes #23236 - fix for choria puppetrun on ubuntu
  modules/puppet_proxy_mcollective/mcollective_main.rb
  test/puppet/mcollective_test.rb
Labels: Needs testing
