Repository theforeman/smart-proxy, pull requests merged in 2018-06, with the labels that each got.

#588 [CP 1.17] Fixes #23433 - lease uids are now parsed correctly
  modules/dhcp_common/isc/configuration_parser.rb
  test/dhcp/conf_parser_test.rb
Labels: Ready to merge

#587 fixes #23917 - convert tls version to string
  lib/launcher.rb
Labels: Needs re-review, Needs testing

#589 [CP 1.17] fixes #23917 - convert tls version to string
  lib/launcher.rb
Labels: Ready to merge

#590 [CP 1.18] fixes #23917 - convert tls version to string
  lib/launcher.rb
Labels: Needs testing, Not yet reviewed

#591 Fixes #24016 - Allow building a tarball without bundle
  Rakefile.dist
  tasks/pkg.rake
Labels: Needs testing

#586 Fixes #23799 - Refactor: Make PuppetCa pluggable
  config/settings.d/puppetca.yml.example
  config/settings.d/puppetca_hostname_whitelisting.yml.example
  extra/migrations/2018062000000_migrate_puppetca_settings.rb
  lib/smart_proxy_main.rb
  modules/puppetca/dependency_injection.rb
  modules/puppetca/plugin_configuration.rb
  modules/puppetca/puppetca.rb
  modules/puppetca/puppetca_api.rb
  modules/puppetca/puppetca_plugin.rb
  modules/puppetca/puppetca_puppet_cert.rb
  modules/puppetca_hostname_whitelisting/plugin_configuration.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_plugin.rb
  test/puppetca/puppetca_config_test.rb
  test/puppetca/puppetca_puppet_cert_test.rb
  test/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner_test.rb
  test/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_config_test.rb
Labels: Ready to merge
