Repository theforeman/smart-proxy, pull requests merged in 2018-08, with the labels that each got.

#599 Generate source with the actual version specified in VERSION
  tasks/pkg.rake
Labels: Needs testing, Waiting on contributor

#598 Fixes #24364 - non-ascii logs are readable now [CP 1.18]
  lib/proxy/log_buffer/decorator.rb
  test/log_buffer/decorator_test.rb
Labels: Needs testing, Not yet reviewed

#597 Fixes #24364 - non-ascii logs are readable now [CP 1.19]
  lib/proxy/log_buffer/decorator.rb
  test/log_buffer/decorator_test.rb
Labels: Needs testing, Not yet reviewed

#601 Fixes #24553 - Fix PuppetCa migrations
  extra/migrations/2018062000000_migrate_puppetca_settings.rb
Labels: Needs testing, Not yet reviewed

#603 Fixes #24591 - fixed debug message in MSDHCP
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
Labels: Needs testing

#605 Fixes #24631 - httpboot module
  config/settings.d/httpboot.yml.example
  lib/launcher.rb
  lib/smart_proxy_main.rb
  modules/httpboot/http_config.ru
  modules/httpboot/httpboot.rb
  modules/httpboot/httpboot_api.rb
  modules/httpboot/httpboot_plugin.rb
  test/httpboot/httpboot_api_test.rb
Labels: Ready to merge

#592 Fixes #23211 - Add PuppetCa TokenWhitelisting provider
  bundler.d/puppetca_token_whitelisting.rb
  config/settings.d/puppetca.yml.example
  config/settings.d/puppetca_token_whitelisting.yml.example
  extra/puppet_sign.rb
  lib/smart_proxy_main.rb
  modules/puppetca/puppetca_api.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner.rb
  modules/puppetca_token_whitelisting/plugin_configuration.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_csr.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_plugin.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_token_storage.rb
  test/fixtures/puppetca/csr_example.pem
  test/fixtures/puppetca/rsa_cert.pem
  test/fixtures/puppetca/storage.yml
  test/fixtures/puppetca/tokens.yml
  test/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner_test.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner_test.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_config_test.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_csr_test.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_token_storage_test.rb
Labels: Needs testing
