Repository theforeman/smart-proxy, pull requests merged in 2019-06, with the labels that each got.

#653 Fixes #26962 - put session id into mdc too
  config/settings.yml.example
  lib/proxy/request_id_middleware.rb
  lib/proxy/settings/global.rb
Labels: Needs testing

#654 Fixes #26979 - Remove Ruby 1.x compatibility code
  Rakefile
  extra/query.rb
  extra/register-service.rb
  lib/checks.rb
  lib/daemon.rb
  lib/proxy/settings/global.rb
  lib/proxy/util.rb
  lib/smart_proxy_for_testing.rb
  lib/smart_proxy_main.rb
  modules/dhcp_common/pingable.rb
  modules/dhcp_common/subnet.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  modules/puppet_proxy_ssh/puppet_proxy_ssh_main.rb
  test/puppet/puppet_api_v3_environment_classes_retriever_test.rb
  test/puppet/puppetssh_test.rb
  test/realm_freeipa/freeipa_provider_test.rb
  test/util_test.rb
Labels: Needs re-review, Needs testing

#606 fixes #24885 - proxy cloud-init nocloud templates
  modules/templates/http_config.ru
  modules/templates/proxy_request.rb
  modules/templates/template_proxy_request.rb
  modules/templates/templates_unattended_api.rb
  modules/templates/templates_userdata_api.rb
  modules/templates/userdata_proxy_request.rb
  test/templates/templates_unattended_api_test.rb
  test/templates/templates_userdata_api_test.rb
Labels: Needs re-review, Needs testing

#649 Fixes #26742 - use Ruby 2.0 compatible gem versions
  bundler.d/dhcp_isc.rb
  bundler.d/test.rb
Labels: Needs testing

#662 Fixes #26742 - use Ruby 2.0 compatible gem versions
  bundler.d/dhcp_isc.rb
  bundler.d/test.rb
Labels: Needs testing, Not yet reviewed

#663 Fixes #26742 - use Ruby 2.0 compatible gem versions
  bundler.d/dhcp_isc.rb
  bundler.d/test.rb
Labels: Needs testing, Not yet reviewed

#664 Fixes #26742 - use Ruby 2.0 compatible gem versions
  bundler.d/dhcp_isc.rb
  bundler.d/test.rb
Labels: Needs testing, Not yet reviewed
