Repository theforeman/smart-proxy, pull requests merged in 2019-01, with the labels that each got.

#627 Fixes #23353 - included DHCP files default directory
  modules/dhcp_common/isc/configuration_parser.rb
  test/dhcp/conf_parser_test.rb
  test/fixtures/dhcp/dhcp_include_relative_testcase1.conf
  test/fixtures/dhcp/dhcp_include_relative_testcase2.conf
Labels: Needs testing

#628 Fixes #25824 - BMC provider nil exception test fixed
  test/bmc/bmc_api_test.rb
Labels: Needs testing, Not yet reviewed

#629 Fixes #25824 - BMC provider nil exception test fixed
  test/bmc/bmc_api_test.rb
Labels: Needs testing, Not yet reviewed

#630 Fixes #25824 - BMC provider nil exception test fixed
  test/bmc/bmc_api_test.rb
Labels: Needs testing, Not yet reviewed

#631 Fixes #25824 - BMC provider nil exception test fixed
  test/bmc/bmc_api_test.rb
Labels: Needs testing, Not yet reviewed

#626 Fixes #25825 - fixed BMC SSH config names
  README.md
  modules/bmc/ssh.rb
  test/bmc/bmc_api_shell_test.rb
  test/bmc/bmc_api_ssh_test.rb
Labels: Needs testing

#617 Fixes #25244 - structured logging of exceptions
  lib/launcher.rb
  lib/proxy/kerberos.rb
  lib/proxy/log_buffer/decorator.rb
  lib/proxy/plugin_initializer.rb
  lib/proxy/util.rb
  modules/dhcp_common/free_ips.rb
  modules/dhcp_libvirt/dhcp_libvirt_main.rb
  modules/dhcp_libvirt/subnet_service_initializer.rb
  modules/dns_dnscmd/dns_dnscmd_main.rb
  modules/dns_libvirt/dns_libvirt_main.rb
  modules/puppet_proxy_puppet_api/v3_environment_classes_api_classes_retriever.rb
  test/log_buffer/decorator_test.rb
Labels: Needs testing, Not yet reviewed

#633 Refs #15095 - improve cache debug logging
  modules/puppet_proxy_puppet_api/v3_environment_classes_api_classes_retriever.rb
Labels: Needs testing

#635 Show rubocop results in STDOUT in jenkins:rubocop
  tasks/jenkins.rake
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#625 Fixes #25614 - v2 Features api with Capabilities and exposed settings
  lib/proxy/pluggable.rb
  lib/proxy/plugin_initializer.rb
  modules/root/http_config.ru
  modules/root/root_v2_api.rb
  modules/tftp/tftp_plugin.rb
  test/plugins/plugin_initializer_test.rb
  test/plugins/plugin_test.rb
  test/root/root_v2_api_test.rb
Labels: Needs testing

#632 Fixes #25769 - dhcp conf parser option code fixed
  .gitignore
  modules/dhcp_common/isc/configuration_parser.rb
  test/dhcp/dhcp_isc_subnet_service_initialization_test.rb
Labels: Needs testing
