Repository theforeman/smart-proxy, pull requests merged in 2020-02, with the labels that each got.

#692 Fixes #29055 - Declare the smart proxy Ruby 2.5+
  Gemfile
  bundler.d/development.rb
  bundler.d/dhcp_isc.rb
  bundler.d/puppetca_token_whitelisting.rb
  bundler.d/realm_freeipa.rb
  bundler.d/test.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_token_storage.rb
  smart_proxy.gemspec
Labels: Needs testing

#693 Fixes #29072 - Update Rubocop to 0.75
  .rubocop.yml
  .rubocop_todo.yml
  bundler.d/test.rb
Labels: Needs testing

#696 Fixes #29078 - Fix Style/UnneededCondition cop
  .rubocop_todo.yml
  lib/proxy/log_buffer/decorator.rb
Labels: Needs testing

#695 Fixes #29077 - Fix Style/Encoding cop
  .rubocop_todo.yml
  test/realm_freeipa/freeipa_provider_test.rb
Labels: Needs testing

#694 Fixes #29076 - Fix Gemspec/OrderedDependencies cop
  .rubocop_todo.yml
  smart_proxy.gemspec
Labels: Needs testing

#697 Fixes #29081 - Fix Lint/UnneededCopEnableDirective cop
  .rubocop_todo.yml
  test/puppetca_http_api/ca_v1_api_request_test.rb
  test/puppetca_http_api/puppetca_http_impl_test.rb
Labels: Needs testing

#698 Fixes #29082 - Fix Layout/TrailingWhitespace cop
  .rubocop_todo.yml
  modules/bmc/bmc_plugin.rb
Labels: Needs testing

#699 Fixes #29083 - Fix Performance/InefficientHashSearch cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  lib/proxy/log_buffer/decorator.rb
Labels: Needs testing

#700 Fixes #29084 - Fix Style/UnlessElse cop
  .rubocop_todo.yml
  lib/proxy/helpers.rb
Labels: Needs testing

#701 Fixes #29085 - Fix Style/SafeNavigation cop
  .rubocop_todo.yml
  extra/migrate_settings.rb
  lib/launcher.rb
  lib/proxy/log_buffer/decorator.rb
  lib/proxy/plugin_initializer.rb
  modules/bmc/bmc_api.rb
  modules/dhcp_common/free_ips.rb
  modules/dhcp_common/isc/omapi_provider.rb
  modules/dhcp_common/pingable.rb
  modules/dhcp_isc/inotify_leases_file_observer.rb
  modules/dhcp_isc/isc_state_changes_observer.rb
  modules/dhcp_isc/kqueue_leases_file_observer.rb
  modules/dns_dnscmd/dns_dnscmd_main.rb
Labels: Needs testing

#703 Fixes #29090 - Fix copy-paste bug in dns_dnscmd_main.rb
  modules/dns_dnscmd/dns_dnscmd_main.rb
Labels: Needs testing

#706 Fixes #29101 - Fix Layout/EmptyLinesAroundAccessModifier cop
  .rubocop_todo.yml
  lib/proxy/request.rb
  modules/bmc/base.rb
  test/bmc/bmc_api_shell_test.rb
  test/bmc/bmc_api_test.rb
  test/bmc/bmc_test.rb
Labels: Needs testing

#704 Fixes #29099 - Fix Layout/EmptyLineBetweenDefs cop
  .rubocop_todo.yml
  lib/proxy/pluggable.rb
  modules/tftp/server.rb
  modules/tftp/tftp_api.rb
  test/dns/dns_api_test.rb
  test/plugins/module_loader_test.rb
  test/plugins/plugin_group_test.rb
  test/puppet/puppet_api_test.rb
  test/puppetca/puppetca_api_test.rb
  test/puppetca_http_api/puppetca_http_impl_test.rb
Labels: Needs testing

#707 Fixes #29103 - Fix Layout/EmptyLinesAroundClassBody cop
  .rubocop_todo.yml
  modules/bmc/base.rb
  modules/bmc/ipmi.rb
  modules/bmc/shell.rb
  modules/dhcp_common/record.rb
  modules/facts/facts_api.rb
  modules/root/root_v2_api.rb
  test/bmc/bmc_api_shell_test.rb
  test/bmc/bmc_test.rb
  test/dhcp/ipv4_address_arithmetic_test.rb
  test/dhcp/record_test.rb
  test/dhcp/server_test.rb
  test/memory_store_test.rb
  test/migrations/dns_migration_test.rb
  test/migrations/libvirt_migration_test.rb
  test/migrations/monolithic_config_file_migration_test.rb
  test/puppet/puppet_api_test.rb
  test/puppetca/puppetca_api_test.rb
  test/root/root_v2_api_test.rb
Labels: Needs testing

#705 Fixes #29100 - Fix Layout/EmptyLines cop
  .rubocop_todo.yml
  test/bmc/bmc_api_test.rb
  test/dhcp/dhcp_api_test.rb
  test/dns/dns_api_test.rb
  test/plugins/module_loader_test.rb
  test/puppetca/puppetca_api_test.rb
  test/request_test.rb
  test/templates/template_proxy_request_test.rb
Labels: Needs testing

#708 Fixes #29105 - Fix Layout/EmptyLinesAroundModuleBody cop
  .rubocop_todo.yml
  lib/proxy/helpers.rb
  lib/proxy/log_buffer/buffer.rb
  lib/proxy/validations.rb
Labels: Needs testing

#710 Fixes #29114 - Fix Style/YodaCondition cop
  .rubocop_todo.yml
  extra/dhcpd_config_check.rb
  extra/migrate_settings.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner_test.rb
Labels: Needs testing

#709 Refs #29072 - Auto-correct new Layout/IndentFirstArgument violations
  .rubocop_todo.yml
  Rakefile
  extra/migrate_settings.rb
  extra/query.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_isc/configuration_loader.rb
  modules/dhcp_libvirt/subnet_service_initializer.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  test/dhcp_ms_native/server_ms_test.rb
  test/migrations/dhcp_migration_test.rb
  test/migrations/migration_test.rb
  test/plugins/plugin_initializer_test.rb
  test/puppet/puppet_class_test.rb
  test/root/root_api_test.rb
  test/root/root_v2_api_test.rb
  test/tftp/tftp_test.rb
Labels: Needs testing, Waiting on contributor

#711 Fixes #29115 - Fix Style/TrivialAccessors cop
  .rubocop_todo.yml
  lib/proxy/plugins.rb
Labels: Needs testing

#714 Fixes #29118 - Fix Style/SingleLineMethods cop
  .rubocop_todo.yml
  test/dependency_injection_test.rb
Labels: Needs testing

#716 Fixes #29120 - Fix Style/RedundantReturn cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/migrations/20150611000000_migrate_dns_settings.rb
  lib/proxy/plugin_validators.rb
  lib/proxy/request.rb
  lib/proxy/util.rb
  modules/bmc/ipmi.rb
  modules/bmc/shell.rb
  modules/dhcp_common/isc/subnet_service_initialization.rb
  modules/dhcp_common/monkey_patches.rb
  modules/dhcp_isc/isc_state_changes_observer.rb
  modules/dns_common/dns_common.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb
  modules/tftp/server.rb
Labels: Needs testing

#715 Fixes #29119 - Fix Style/SelfAssignment cop
  .rubocop_todo.yml
  lib/proxy/helpers.rb
  lib/proxy/util.rb
Labels: Needs testing

#712 Fixes #29116 - Fix Style/StringLiteralsInInterpolation cop
  .rubocop_todo.yml
  Rakefile
  extra/dhcpd_config_check.rb
  extra/query.rb
  lib/proxy/log.rb
Labels: Needs testing

#718 Fixes #29123 - Fix Style/OrAssignment cop
  .rubocop_todo.yml
  extra/query.rb
Labels: Needs testing

#720 Fixes #29126 - Disable cops, that are disabled in core
  .rubocop.yml
  .rubocop_todo.yml
Labels: Needs testing

#713 Fixes #29117 - Fix Style/SpecialGlobalVars cop
  .rubocop_todo.yml
  extra/dhcpd_config_check.rb
  extra/migrate_settings.rb
  extra/query.rb
  lib/proxy/util.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  tasks/jenkins.rake
  tasks/pkg.rake
  test/test_helper.rb
Labels: Needs testing

#721 Fixes #29127 - Fix Style/SymbolProc cop
  .rubocop.yml
  lib/proxy/plugin_initializer.rb
  modules/dhcp_common/free_ips.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner.rb
  modules/tftp/server.rb
  test/puppet/puppet_api_environments_retriever_test.rb
Labels: Needs testing

#723 Fixes #29129 - Fix Layout/IndentationWidth cop
  .rubocop_todo.yml
  lib/proxy/helpers.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  modules/dns/dns_api.rb
  modules/dns_common/dns_common.rb
  modules/tftp/tftp_api.rb
  tasks/proxy_tasks.rake
  test/dhcp/conf_parser_test.rb
  test/dhcp/subnet_test.rb
  test/http_download_test.rb
  test/puppetca_puppet_cert/puppetca_puppet_cert_test.rb
Labels: Needs testing

#725 Fixes #29132 - Drop mail_patches rake task
  Rakefile
  tasks/proxy_tasks.rake
Labels: Needs testing, Not yet reviewed

#717 Fixes #29121 - Fix Style/RedundantBegin cop
  .rubocop_todo.yml
  lib/proxy/util.rb
  modules/dhcp/dhcp_api.rb
  modules/dhcp_common/pingable.rb
  modules/facts/facts_api.rb
  modules/facts/facts_plugin.rb
  modules/logs/logs_api.rb
  modules/logs/logs_plugin.rb
  modules/puppet_proxy/puppet_api.rb
  modules/puppetca/puppetca_api.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_token_storage.rb
  modules/realm/realm_api.rb
  modules/root/root_api.rb
  modules/root/root_v2_api.rb
  modules/templates/templates_unattended_api.rb
Labels: Needs testing

#724 Fixes #29130 - Fix Layout/IndentationConsistency cop
  .rubocop_todo.yml
  lib/proxy/helpers.rb
Labels: Needs testing

#727 Refs #29130 - Fix inconsistent indentation
  modules/logs/logs_plugin.rb
Labels: Needs testing, Not yet reviewed

#726 Fixes #29137 - Case insensitive version cleanup
  lib/proxy/pluggable.rb
Labels: Needs testing

#722 Fixes #29128 - Fix Style/Lambda cop
  .rubocop.yml
  lib/proxy/settings/global.rb
  modules/dhcp_isc/configuration_loader.rb
  modules/dhcp_libvirt/configuration_loader.rb
  modules/dhcp_native_ms/plugin_configuration.rb
  modules/dns_dnscmd/plugin_configuration.rb
  modules/dns_libvirt/plugin_configuration.rb
  modules/dns_nsupdate/nsupdate_configuration.rb
  modules/dns_nsupdate/nsupdate_gss_configuration.rb
  modules/puppet_proxy_puppet_api/plugin_configuration.rb
  modules/puppetca_hostname_whitelisting/plugin_configuration.rb
  modules/puppetca_http_api/plugin_configuration.rb
  modules/puppetca_puppet_cert/plugin_configuration.rb
  modules/puppetca_token_whitelisting/plugin_configuration.rb
  modules/realm_freeipa/configuration_loader.rb
  test/dependency_injection_test.rb
  test/global_settings_test.rb
  test/plugins/module_loader_test.rb
  test/plugins/plugin_initializer_test.rb
  test/plugins/validator_test.rb
  test/puppetca/puppetca_api_test.rb
  test/root/root_v2_api_test.rb
Labels: Needs testing

#732 Fixes #29154 - Fix Layout/TrailingBlankLines cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/register-service.rb
  lib/bundler_helper.rb
  lib/proxy/file_lock.rb
  modules/bmc/bmc_plugin.rb
  modules/puppetca_hostname_whitelisting/plugin_configuration.rb
  modules/puppetca_token_whitelisting/plugin_configuration.rb
  modules/tftp/tftp.rb
  tasks/jenkins.rake
  test/dns_nsupdate/dns_nsupdate_config_test.rb
  test/migrations/1_test_migration_one.rb
  test/migrations/2_test_migration_two.rb
  test/migrations/3_test_migration_three.rb
  test/migrations/autosign_migration_test.rb
  test/migrations/puppet_migration_test.rb
  test/migrations/realm_migration_test.rb
Labels: Needs testing

#730 Fixes #29152 - Fix Layout/LeadingCommentSpace cop
  .rubocop_todo.yml
  lib/proxy/plugin_initializer.rb
  modules/bmc/bmc_api.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_common/isc/subnet_service_initialization.rb
  modules/dhcp_common/record.rb
  modules/dns_common/dns_common.rb
  modules/puppet_proxy_puppet_api/v3_environment_classes_api_classes_retriever.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner.rb
  test/bmc/bmc_api_test.rb
  test/dhcp_libvirt/libvirt_dhcp_network_test.rb
  test/sinatra/trusted_hosts_test.rb
Labels: Needs testing

#729 Fixes #29151 - Fix Layout/EmptyLinesAroundMethodBody cop
  .rubocop_todo.yml
  modules/dhcp_native_ms/plugin_configuration.rb
Labels: Needs testing

#728 Fixes #29150 - Fix Layout/ClosingParenthesisIndentation cop
  .rubocop_todo.yml
  extra/query.rb
Labels: Needs testing

#733 Fixes #29155 - Fix Lint/UnneededRequireStatement
  .rubocop_todo.yml
  lib/launcher.rb
  lib/proxy/dependency_injection.rb
  lib/proxy/log_buffer/decorator.rb
  lib/proxy/log_buffer/trace_decorator.rb
Labels: Needs testing

#719 Sort Rubocop rules
  .rubocop.yml
Labels: Needs re-review, Needs testing, Waiting on contributor

#731 Fixes #29153 - Fix Layout/SpaceInsideParens cop
  .rubocop_todo.yml
  modules/dhcp_common/isc/configuration_parser.rb
Labels: Needs testing

#736 Fixes #29158 - Fix Style/Multiline*Then cops
  .rubocop_todo.yml
  extra/dhcpd_config_check.rb
  extra/migrate_settings.rb
  modules/dhcp_libvirt/subnet_service_initializer.rb
  modules/dns_common/dns_common.rb
Labels: Needs testing

#737 Fixes #29159 - Fix Style/For cop
  .rubocop_todo.yml
  extra/query.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
Labels: Needs testing

#735 Fixes #29157 - Fix Style/NegatedIf cop
  .rubocop_todo.yml
  extra/changelog
  extra/migrations/20150611000000_migrate_dns_settings.rb
  extra/migrations/20150826000000_migrate_dhcp_settings.rb
  extra/migrations/20160413000000_migrate_puppet_settings.rb
  extra/migrations/20161209000000_migrate_realm_settings.rb
  extra/migrations/20170523000000_migrate_autosign_setting.rb
  lib/proxy/plugin_initializer.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
Labels: Needs testing

#738 Fixes #29160 - Fix Layout/ExtraSpacing cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/migrations/2018062000000_migrate_puppetca_settings.rb
  extra/migrations/20181016000000_migrate_puppetca_puppet_cert_settings.rb
  extra/puppet_sign.rb
  lib/proxy/http_download.rb
  modules/bmc/ipmi.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_common/isc/omapi_provider.rb
  modules/dns_dnscmd/dns_dnscmd_main.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  test/dhcp/conf_parser_test.rb
  test/dhcp/dhcp_api_test.rb
  test/dhcp/dhcp_isc_subnet_service_initialization_test.rb
  test/dhcp_libvirt/dhcp_libvirt_provider_test.rb
  test/dns_common/record_test.rb
  test/dns_dnscmd/dnscmd_test.rb
  test/puppet/puppet_api_environments_retriever_test.rb
Labels: Needs testing

#739 Fixes #29161 - Fix Layout/IndentHeredoc cop
  .rubocop_todo.yml
  smart_proxy.gemspec
  test/dhcp/conf_parser_test.rb
  test/dhcp/dhcp_isc_subnet_service_initialization_test.rb
  test/dhcp_libvirt/subnet_service_initializer_test.rb
  test/dns_libvirt/dns_libvirt_provider_test.rb
  test/puppet/puppet_api_v3_environment_classes_retriever_test.rb
  test/puppetca_puppet_cert/puppetca_puppet_cert_test.rb
  test/realm/ipa_config_parser_test.rb
Labels: Needs testing

#741 Fixes #29137 - Case insensitive version cleanup (2.0-stable)
  lib/proxy/pluggable.rb
Labels: Needs testing

#742 Fixes #29171 - Fix Style/TernaryParentheses cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/migrations/20160413000000_migrate_puppet_settings.rb
  extra/puppet_sign.rb
  modules/dhcp_common/subnet.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  modules/dns/dns_api.rb
  modules/puppetca/plugin_configuration.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb
  test/dns_common/record_test.rb
Labels: Needs testing

#744 Fixes #29173 - Fix Layout/SpaceAfterComma cop
  .rubocop_todo.yml
  Rakefile
  extra/changelog
  extra/migrate_settings.rb
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/migrations/20150611000000_migrate_dns_settings.rb
  extra/migrations/20150826000000_migrate_dhcp_settings.rb
  extra/migrations/20160413000000_migrate_puppet_settings.rb
  extra/migrations/20161209000000_migrate_realm_settings.rb
  extra/migrations/20170523000000_migrate_autosign_setting.rb
  lib/proxy/log.rb
  lib/proxy/request.rb
  lib/proxy/settings.rb
  lib/proxy/settings/global.rb
  lib/proxy/util.rb
  modules/dhcp_common/record/lease.rb
  modules/dns/dns_api.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  modules/templates/proxy_request.rb
  modules/tftp/server.rb
  test/bmc/bmc_api_test.rb
  test/dhcp/record_test.rb
  test/dns_common/record_test.rb
  test/dns_dnscmd/dnscmd_test.rb
  test/global_settings_test.rb
  test/log_buffer/decorator_test.rb
  test/migrations/autosign_migration_test.rb
  test/migrations/dhcp_migration_test.rb
  test/migrations/dns_migration_test.rb
  test/migrations/libvirt_migration_test.rb
  test/migrations/migration_test.rb
  test/migrations/monolithic_config_file_migration_test.rb
  test/migrations/puppet_migration_test.rb
  test/migrations/realm_migration_test.rb
  test/puppetca_puppet_cert/puppetca_puppet_cert_test.rb
  test/test_helper.rb
  test/tftp/tftp_api_test.rb
  test/tftp/tftp_test.rb
Labels: Needs testing

#745 Fixes #25369 - Fix Lint/StringConversionInInterpolation cop
  .rubocop_todo.yml
  extra/migrations/20150327000000_migrate_monolithic_config.rb
Labels: Needs testing

#746 Fixes #29175 - Fix Style/Alias cop
  .rubocop_todo.yml
  modules/dns_libvirt/dns_libvirt_main.rb
  test/sinatra/ssl_client_verification_integration_test.rb
Labels: Needs testing

#747 Fixes #29176 - Fix Style/MethodDefParentheses cop
  .rubocop_todo.yml
  lib/proxy/dependency_injection.rb
  lib/proxy/helpers.rb
  lib/proxy/kerberos.rb
  lib/proxy/validations.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_common/isc/omapi_provider.rb
  modules/dhcp_common/isc/subnet_service_initialization.rb
  modules/dhcp_common/monkey_patch_subnet.rb
  modules/dhcp_common/pingable.rb
  modules/dhcp_common/record.rb
  modules/dhcp_common/record/reservation.rb
  modules/dhcp_common/server.rb
  modules/dhcp_common/subnet.rb
  modules/dns_common/dns_common.rb
  modules/dns_dnscmd/dns_dnscmd_main.rb
  modules/dns_libvirt/dns_libvirt_main.rb
  modules/dns_nsupdate/dns_nsupdate_main.rb
  modules/libvirt_common/libvirt_network.rb
  modules/puppet_proxy_common/puppet_class.rb
  modules/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_autosigner.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_token_storage.rb
  modules/realm_freeipa/provider.rb
  modules/tftp/server.rb
  modules/tftp/tftp_api.rb
  test/dhcp/isc_omapi_provider_test.rb
Labels: Needs testing

#749 Fixes #29162 - Update Rubocop to 0.80
  .rubocop.yml
  .rubocop_todo.yml
  bundler.d/test.rb
  lib/proxy/http_download.rb
  modules/dhcp/dhcp_api.rb
  tasks/jenkins.rake
  test/log_buffer/decorator_test.rb
Labels: Needs testing

#743 Fixes #29172 - Fix Layout/SpaceBeforeBlockBraces cop
  .rubocop_todo.yml
  config.ru
  extra/dhcpd_config_check.rb
  extra/migrate_settings.rb
  extra/migrations/20150327000000_migrate_monolithic_config.rb
  extra/migrations/20160413000000_migrate_puppet_settings.rb
  extra/register-service.rb
  lib/launcher.rb
  lib/proxy/log.rb
  lib/proxy/log_buffer/buffer.rb
  lib/proxy/pluggable.rb
  lib/proxy/plugin_initializer.rb
  lib/proxy/plugins.rb
  lib/proxy/request.rb
  modules/dhcp/dependency_injection.rb
  modules/dhcp/dhcp_api.rb
  modules/dhcp_common/isc/configuration_parser.rb
  modules/dhcp_common/isc/omapi_provider.rb
  modules/dhcp_common/isc/subnet_service_initialization.rb
  modules/dhcp_common/record/lease.rb
  modules/dhcp_common/record/reservation.rb
  modules/dhcp_common/server.rb
  modules/dhcp_common/subnet.rb
  modules/dhcp_isc/configuration_loader.rb
  modules/dhcp_libvirt/configuration_loader.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  modules/dhcp_native_ms/plugin_configuration.rb
  modules/dns/dependency_injection.rb
  modules/dns_common/dependency_injection/dependencies.rb
  modules/dns_common/dns_common.rb
  modules/dns_dnscmd/plugin_configuration.rb
  modules/dns_libvirt/plugin_configuration.rb
  modules/dns_nsupdate/nsupdate_configuration.rb
  modules/puppet_proxy/dependency_injection.rb
  modules/puppet_proxy/puppet_api.rb
  modules/puppet_proxy_common/api_request.rb
  modules/puppet_proxy_puppet_api/plugin_configuration.rb
  modules/puppetca/dependency_injection.rb
  modules/puppetca_puppet_cert/puppetca_impl.rb
  modules/realm/dependency_injection.rb
  modules/realm_freeipa/configuration_loader.rb
  modules/root/root_api.rb
  modules/root/root_v2_api.rb
  modules/templates/proxy_request.rb
  modules/tftp/server.rb
  modules/tftp/tftp_api.rb
  test/bmc/bmc_api_test.rb
  test/dhcp/conf_parser_test.rb
  test/dhcp/dhcp_api_test.rb
  test/dhcp/free_ips_test.rb
  test/dhcp_libvirt/production_di_wirings_test.rb
  test/dns_common/record_test.rb
  test/plugins/module_loader_test.rb
  test/plugins/plugin_initializer_test.rb
  test/plugins/plugin_test.rb
  test/plugins/validator_test.rb
  test/realm_freeipa/freeipa_provider_test.rb
  test/root/root_api_test.rb
  test/test_helper.rb
  test/tftp/tftp_server_test.rb
Labels: Needs testing, Waiting on contributor
