Repository theforeman/smart-proxy, pull requests merged in 2021-11, with the labels that each got.

#793 fixes #18069 - Add ip/mac Addr. validations (DHCP)
  .gitignore
  lib/proxy/validations.rb
  modules/dhcp/dhcp_api.rb
  modules/dhcp_common/isc/omapi_provider.rb
  modules/dhcp_common/server.rb
  modules/dhcp_libvirt/dhcp_libvirt_main.rb
  modules/dhcp_native_ms/dhcp_native_ms_main.rb
  test/dhcp/dhcp_api_test.rb
  test/dhcp/record_test.rb
  test/dhcp/subnet_test.rb
  test/validations_test.rb
Labels: Needs re-review, Needs testing

#802 Fixes #33756 - Require 'templates' for 'registration' module
  modules/registration/registration_plugin.rb
  test/registration/integration_test.rb
Labels: Needs testing

#799 Refs #2412 - use curl for downloads
  config/settings.d/tftp.yml.example
  lib/proxy/http_download.rb
  lib/proxy/util.rb
  modules/tftp/server.rb
  modules/tftp/tftp_plugin.rb
  test/http_download_test.rb
  test/tftp/tftp_test.rb
Labels: Needs testing

#805 Fixes #33915 - Bump develop to 3.2.0-develop
  VERSION
Labels: Needs testing, Not yet reviewed
