Repository theforeman/smart-proxy, pull requests merged in 2022-08, with the labels that each got.

#839 Update develop to 3.5.0-develop
  VERSION
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#842 Fixes #35384 - Add missing require 'timeout'
  modules/dns_dnscmd/dns_dnscmd_main.rb
Labels: Needs testing, Not yet reviewed

#844 Fixes #35468 - Verify boolean settings in modules
  modules/dhcp/dhcp_plugin.rb
  modules/dhcp_native_ms/dhcp_native_ms_plugin.rb
  modules/puppetca_token_whitelisting/puppetca_token_whitelisting_plugin.rb
  modules/realm_freeipa/realm_freeipa_plugin.rb
  modules/tftp/tftp_plugin.rb
Labels: Needs testing
