Repository theforeman/smart-proxy, pull requests merged in 2022-03, with the labels that each got.

#807 Fixes #34162 - Allow calling load_test_settings without settings
  lib/smart_proxy_for_testing.rb
  test/dhcp/dhcp_config_test.rb
  test/dhcp/server_test.rb
  test/dhcp_isc/dhcp_isc_config_test.rb
  test/dhcp_libvirt/dhcp_libvirt_config_test.rb
  test/dns/dns_config_test.rb
  test/dns_dnscmd/dnscmd_config_test.rb
  test/dns_libvirt/dns_libvirt_configuration_test.rb
  test/dns_nsupdate/dns_nsupdate_config_test.rb
  test/plugins/validator_test.rb
  test/puppet/puppet_api_configuration_test.rb
  test/puppetca/puppetca_config_test.rb
  test/puppetca_hostname_whitelisting/puppetca_hostname_whitelisting_config_test.rb
  test/puppetca_http_api/puppetca_http_api_config_test.rb
  test/puppetca_puppet_cert/puppetca_puppet_cert_config_test.rb
  test/puppetca_token_whitelisting/puppetca_token_whitelisting_config_test.rb
  test/tftp/tftp_test.rb
Labels: Needs testing

#821 Update minimum Puppet version in README
  README.md
Labels: Needs testing, Waiting on contributor

#661 Fixes #27088 - Handle capabilities for uninitialized plugins
  modules/root/root_v2_api.rb
  test/bmc/integration_test.rb
Labels: Needs testing

#823 Fixes #34564 - Drop single_test gem dependency
  bundler.d/development.rb
  bundler.d/test.rb
Labels: Needs testing, Not yet reviewed

#824 Fixes #34566 - Refactor validate_ip to use a case statement
  lib/proxy/validations.rb
Labels: Needs testing

#826 Fixes #34589 - Remove duplicate rsec gem definition
  bundler.d/dhcp_isc.rb
Labels: Needs testing

#828 Fixes #34624 - Set MALLOC_ARENA_MAX to counter memory bloating
  extra/systemd/foreman-proxy.service
Labels: Needs testing

#827 Fixes #34613 - Verify SSL CA file is readable on startup
  lib/launcher.rb
Labels: Needs testing

#830 Fixes #34624 - Set MALLOC_ARENA_MAX to counter memory bloating
  extra/systemd/foreman-proxy.service
Labels: Needs testing

#831 Fixes #34624 - Set MALLOC_ARENA_MAX to counter memory bloating
  extra/systemd/foreman-proxy.service
Labels: Needs testing
