Repository theforeman/smart-proxy, pull requests merged in 2022-02, with the labels that each got.

#809 Fixes #34164 - Add enum plugin validator
  lib/proxy/default_plugin_validators.rb
  lib/proxy/plugin_validators.rb
  test/plugins/validator_test.rb
Labels: Needs testing

#819 Bump develop to 3.3.0-develop
  VERSION
Labels: Needs testing, Waiting on contributor

#817 Fixes #34359 - fix DHCP IP validation arguments tests
  modules/dhcp_common/server.rb
  test/dhcp/dhcp_api_test.rb
  test/dhcp/integration_test.rb
  test/dhcp/isc_omapi_provider_test.rb
  test/dhcp/server_test.rb
  test/dhcp_isc/root_integration_test.rb
  test/dhcp_libvirt/dhcp_libvirt_provider_test.rb
  test/dhcp_ms_native/server_ms_test.rb
Labels: Needs testing

#820 Fixes #34359 - fix DHCP IP validation arguments tests
  modules/dhcp_common/server.rb
  test/dhcp/dhcp_api_test.rb
  test/dhcp/integration_test.rb
  test/dhcp/isc_omapi_provider_test.rb
  test/dhcp/server_test.rb
  test/dhcp_isc/root_integration_test.rb
  test/dhcp_libvirt/dhcp_libvirt_provider_test.rb
  test/dhcp_ms_native/server_ms_test.rb
Labels: Needs testing, Not yet reviewed
